name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: PrepLAB1
      id: preplab1
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 5
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PREPLAB1_RESULTS: "${{steps.preplab1.outputs.result}}"
      with:
        runners: preplab1
